version: "3.10"
services:
  db:
    container_name: todolist-db
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 3

  api:
    image: edenerus/todolist:latest
    restart: always
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_static:/todolist/static

  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - /nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static


volumes:
  todolist_pg_data:
    driver: local
  django_static:
    driver: local